---
# tasks file for java

- name: Update repos
  yum:
    name: "*"
    state: latest



- name: Install Java
  yum: 
    name: "{{ java_version}}"
    state: present

- name: Fetch Java version
  shell: java -version 2>&1 | grep version | awk '{print $3}' | sed 's/"//g'                                                                                                                                   
  changed_when: False
  register: java_result

- debug:
    msg: "{{ java_result.stdout}}"




      

  